Repository LIKELION-Android-Bootcamp-4th/FinalProject-GureumPage-HIHIHIHI, pull requests merged in 2025-08, with the labels that each got.

#52 [Feat] navigation 구현
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/NavigationRoute.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/LoginScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/MindMapScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/OnBoardingScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onborading/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/QuotesScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerScreen.kt
Labels: Feature

#53 [refactor] 앱 컬러 추가 및 변경
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/Color.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/GureumColor.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/Theme.kt
Labels: Refactoring

#54 [Build] data, presentation 모듈에 라이브러리 추가
  build.gradle.kts
  data/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: Feature

#55 [Feat] 컬러 지정 방법 변경 및 앱 컬러 사용 스타일 변경
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/GureumBackground.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/GureumColor.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/GureumColors.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/Theme.kt
Labels: Feature

#61 [Hotfix] 라이브러리 버전 없거나 충돌나던거 해결
  build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  settings.gradle.kts
Labels: Fix

#72 [Feat] statistics 화면 UI 구현
  presentation/src/main/java/com/hihihihi/gureumpage/common/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/component/.gitkeep
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumText.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/GureumColors.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/Theme.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/Type.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/GenreCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/ReadingPageCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/ReadingTimeCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/mock.kt
Labels: Feature, UI

#76 [Feat] library UI refactor
  presentation/build.gradle.kts
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/BookItem.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/Library_toggleTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/model/Book.kt
Labels: Refactoring, UI

#80 [Feat] 서재 기능 구현
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/BookItem.kt
Labels: Feature, Refactoring

#82 [Feat] bookdetail 화면 UI 구현
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumChip.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumText.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailFab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailTabs.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookSimpleInfoSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookStatisticsCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/ReadingProgressSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/BookInfoTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/QuotesTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/ReadingRecordTab.kt
Labels: Feature, UI

#81 [Feat] 홈 검색바 및 독서중인 책 UI 완성
  data/src/main/java/com/hihihihi/data/common/util/utils.kt
  data/src/main/java/com/hihihihi/data/mapper/UserBookMapper.kt
  data/src/main/java/com/hihihihi/data/remote/dto/UserBookDto.kt
  domain/src/main/java/com/hihihihi/domain/model/UserBook.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/Floating.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumProgressBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/CurrentReadingBookSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/SearchBarWithBackground.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/mock/Mock.kt
  presentation/src/main/res/drawable/bg_home_dark.png
  presentation/src/main/res/drawable/ic_cloud_reading.png
Labels: UI

#84 [Feat] 현재 독서중인 책 기능 추가
  data/src/main/java/com/hihihihi/data/mapper/UserBookMapper.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/UserBookRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/UserBookRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/dto/UserBookDto.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/UserBookRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/model/UserBook.kt
  domain/src/main/java/com/hihihihi/domain/repository/UserBookRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/userbook/GetUserBooksByStatusUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
Labels: Feature, Fix

#85 [Feat] 서재 기능 피드백 반영
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryViewModel.kt
Labels: Refactoring

#89 [Feat] 필사 UI 피드백 반영
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/DetailBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteContent.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteItem.kt
Labels: Refactoring, UI

#90 [Feat] 필사한 문장 UI 및 기능 완성
  data/src/main/java/com/hihihihi/data/mapper/QuoteMapper.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/QuoteRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/dto/QuoteDto.kt
  domain/src/main/java/com/hihihihi/domain/model/Quote.kt
  presentation/build.gradle.kts
  presentation/src/main/assets/cloud_bulb.json
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/CurrentReadingBookSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/RandomQuoteSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/SearchBarWithBackground.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/mock/Mock.kt
Labels: Feature, UI

#91 [Feat] 오늘 목표 달성 UI 완성
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumProgressBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/CurrentReadingBookSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/GureumNumberPicker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/Picker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/RandomQuoteSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalPicker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalSection.kt
  presentation/src/main/res/drawable/bg_book_25.png
  presentation/src/main/res/drawable/bg_book_50.png
  presentation/src/main/res/drawable/bg_book_75.png
Labels: UI

#96 [Feat] 커스텀 앱바 구현
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumAppBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteContent.kt
Labels: Feature, UI

#99 [Feat] search 관련 통신
  data/build.gradle.kts
  data/src/main/java/com/hihihihi/data/di/DataSourceModule.kt
  data/src/main/java/com/hihihihi/data/di/RepositoryModule.kt
  data/src/main/java/com/hihihihi/data/di/RetrofitModule.kt
  data/src/main/java/com/hihihihi/data/mapper/SearchBookMapper.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/SearchRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/SearchRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/dto/BookDetailDto.kt
  data/src/main/java/com/hihihihi/data/remote/dto/SearchBookDto.kt
  data/src/main/java/com/hihihihi/data/remote/service/SearchApiService.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/SearchRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/model/SearchBook.kt
  domain/src/main/java/com/hihihihi/domain/repository/SearchRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/search/SearchBooksUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/LoginScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/DatePickTextField.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/SearchItem.kt
Labels: Feature

#98 [Feat] onboarding 화면 UI 구현 완료 및 기능 일부 구현
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Expansion.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumAppBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumProgressBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumText.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumTextField.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookSimpleInfoSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/ReadingRecordTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/CurrentReadingBookSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/RandomQuoteSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/LoginScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/OnBoardingScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/OnBoardingViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/components/OnboardingBottomContents.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/components/OnboardingMainContents.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/components/OnboardingPurposeCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/components/OnboardingScaffold.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/components/OnboardingThemeCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/components/OnboardingTopContents.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/model/OnboardingFeature.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/model/OnboardingPurposeContents.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/model/OnboardingStep.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/model/ThemeType.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/FeaturePage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/FinishPage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/NicknamePage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/PurposePage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/ThemePage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/WelcomePage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
  presentation/src/main/res/drawable/ic_checked.xml
  presentation/src/main/res/drawable/ic_cloud_library.png
  presentation/src/main/res/drawable/ic_cloud_statistics.png
  presentation/src/main/res/drawable/ic_cloud_timer.png
  presentation/src/main/res/drawable/ic_none_checked.xml
Labels: Feature, UI

#105 [Feat] BookDetail 서버 데이터 적용하기
  data/src/main/java/com/hihihihi/data/di/DataSourceModule.kt
  data/src/main/java/com/hihihihi/data/di/RepositoryModule.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/HistoryRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/QuoteRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/QuoteRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/HistoryRepositoryImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/QuoteRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/repository/HistoryRepository.kt
  domain/src/main/java/com/hihihihi/domain/repository/QuoteRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/userbook/GetBookDetailDataUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/userbook/GetUserBookUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/NavigationRoute.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailFabEvent.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailFab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailTabs.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookStatisticsCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/ReadingProgressSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/BookInfoTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/ReadingRecordTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/FloatingTimerService.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/MindMapScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashScreen.kt
Labels: Feature

#106 [Feat] search adduserbook 관련 누락건
  data/src/main/java/com/hihihihi/data/mapper/UserBookMapper.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/UserBookRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/UserBookRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/UserBookRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/repository/UserBookRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/userbook/AddUserBookUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/ReadingRecordTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
Labels: Feature

#107 [Feat] 책 상세에서 필사 추가 UI 및 로직 구현
  data/src/main/java/com/hihihihi/data/mapper/QuoteMapper.kt
  data/src/main/java/com/hihihihi/data/remote/dto/QuoteDto.kt
  domain/src/main/java/com/hihihihi/domain/model/Quote.kt
  domain/src/main/java/com/hihihihi/domain/usecase/userbook/GetBookDetailDataUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumTextField.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/NavigationRoute.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddQuoteDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/QuotesTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerScreen.kt
Labels: Feature, UI

#110 [Feat] 책 상세에서 직접 기록 추가 UI 및 기능 구현
  data/src/main/java/com/hihihihi/data/remote/datasource/HistoryRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/HistoryRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/repository/HistoryRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/history/.gitkeep
  domain/src/main/java/com/hihihihi/domain/usecase/history/AddHistoryUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/GureumNumberPicker.kt
Labels: Feature, UI

#111 [Feat] statistics 화면 파이어베이스 연동
  data/src/main/java/com/hihihihi/data/remote/datasource/HistoryRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/HistoryRepositoryImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/UserBookRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/model/Statistics.kt
  domain/src/main/java/com/hihihihi/domain/repository/HistoryRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/statistics/GetCategoryStatisticsUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/CategoryCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/GureumStatisticsPicker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/ReadingPageCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/ReadingTimeCard.kt
Labels: Feature, Refactoring

#108 [Feat] mindmap 서버 연동 성공
  data/src/main/java/com/hihihihi/data/di/DataSourceModule.kt
  data/src/main/java/com/hihihihi/data/di/RepositoryModule.kt
  data/src/main/java/com/hihihihi/data/mapper/MindmapMapper.kt
  data/src/main/java/com/hihihihi/data/mapper/MindmapNodeMapper.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/MindmapNodeRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/MindmapRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/UserBookRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/MindmapNodeRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/MindmapRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/UserBookRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/dto/MindmapDto.kt
  data/src/main/java/com/hihihihi/data/remote/dto/MindmapNodeDto.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/MindmapNodeRepositoryImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/MindmapRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/model/Mindmap.kt
  domain/src/main/java/com/hihihihi/domain/model/MindmapNode.kt
  domain/src/main/java/com/hihihihi/domain/operation/NodeEditOperation.kt
  domain/src/main/java/com/hihihihi/domain/repository/MindmapNodeRepository.kt
  domain/src/main/java/com/hihihihi/domain/repository/MindmapRepository.kt
  domain/src/main/java/com/hihihihi/domain/repository/UserBookRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/mindmap/.gitkeep
  domain/src/main/java/com/hihihihi/domain/usecase/mindmap/CreateMindmapUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/mindmap/GetMindmapUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/mindmap/UpdateMindmapUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/mindmapnode/.gitkeep
  domain/src/main/java/com/hihihihi/domain/usecase/mindmapnode/ApplyNodeOperation.kt
  domain/src/main/java/com/hihihihi/domain/usecase/mindmapnode/LoadNodesUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/mindmapnode/ObserveUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/userbook/AddUserBookUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/NavigationRoute.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/MindMapAdapter.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/MindMapScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/MindMapViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/mapper/MindmapMapper.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mindmap/model/MindMapNodeData.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchViewModel.kt
  presentation/src/main/res/layout/item_mindmap_node.xml
Labels: Feature

#114 [Refactor] 통계 계산 안되던 로직 변경, 최초 호출 Screen에서 Viewmodel로 변경
  domain/src/main/java/com/hihihihi/domain/repository/DailyReadPageRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/statistics/GetCategoryStatisticsUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsViewModel.kt
Labels: Feature, Refactoring

#115 [Refactor] 자잘한 부분 리팩토링
  data/src/main/java/com/hihihihi/data/remote/datasource/UserRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/UserRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/UserRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/repository/UserRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/user/GetHomeDataUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/user/UpdateDailyGoalTimeUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/BookItem.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/QuotesViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/DetailBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteContent.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
Labels: Refactoring, Fix

#116 [Feat] 리뷰 및 별점 등록, 저장 로직 구현
  presentation/build.gradle.kts
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/ReviewSection.kt
  presentation/src/main/res/drawable/ic_save_outline.xml
Labels: Feature, UI

#117 [Refactor] 책 상세 1차 리팩토링
  data/src/main/java/com/hihihihi/data/mapper/UserBookMapper.kt
  data/src/main/java/com/hihihihi/data/remote/dto/UserBookDto.kt
  domain/src/main/java/com/hihihihi/domain/model/UserBook.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailFab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookSimpleInfoSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookStatisticsCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/BookInfoTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/QuotesTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/ReadingRecordTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/SearchItem.kt
Labels: Refactoring

#118 [Refactor] 서재 1차 리팩터링
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/SearchBarWithBackground.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/CategoryCard.kt
  presentation/src/main/res/drawable/ic_library_finished.xml
  presentation/src/main/res/drawable/ic_library_planned.xml
Labels: Refactoring, UI

#120 [Feat] 서재 2차 리팩토링
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumTextField.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddQuoteDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/ReadingProgressSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/SetReadingStatusBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/QuotesTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/GureumNumberPicker.kt
Labels: Refactoring

#125 [Feat/Refactor] home 화면 리팩토링
  build.gradle.kts
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
  domain/src/main/java/com/hihihihi/domain/usecase/history/AddHistoryUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/assets/cloud_bulb.json
  presentation/src/main/assets/confetti.json
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/CurrentReadingBookSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/SearchBarWithBackground.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/LoginScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/components/SocialLoginButton.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/FinishPage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/NicknamePage.kt
  presentation/src/main/res/drawable/bg_home_dark.png
  presentation/src/main/res/drawable/bg_home_light.png
  presentation/src/main/res/drawable/ic_cloud_question.png
  presentation/src/main/res/drawable/ic_cloud_reading.png
  presentation/src/main/res/values/themes.xml
Labels: Refactoring, UI

#127 [Feat] 탈퇴 로직 구현
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/NavigationRoute.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/MypageViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/component/MyPageMenuSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/withdraw/WithdrawScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/withdraw/WithdrawUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/withdraw/WithdrawViewModel.kt
Labels: Feature, UI

#128 [Refactor] 내비게이터 및 empty 문구 등
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Expansion.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/ReviewSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/SetReadingStatusBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/BookItem.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/MypageViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/NicknamePage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/QuotesScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/DetailBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteContent.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/EmptyCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/StatisticsPicker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/component/StopReadingDialog.kt
  presentation/src/main/res/drawable/ic_finish_stamp.xml
Labels: Refactoring

#130 [HOTFIX] 텍스트 필드를 모두 비우면 앱이 튕기던 현상 수정
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
Labels: Fix

#131 [Refactor] 타이머 리팩토링
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/component/TimerRing.kt
Labels: Refactoring

#135 [Fix] 독서 기록 추가 후 현재 페이지 업데이트 버그 수정
  data/src/main/java/com/hihihihi/data/remote/datasource/HistoryRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/HistoryRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/repository/HistoryRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/history/AddHistoryUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerViewModel.kt
Labels: Fix

#140 [Fix] 상태바 컬러 오류 수정
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchScreen.kt
  presentation/src/main/res/values/themes.xml
Labels: Fix

#139 [Feat] 책 상세 필사 추가/삭제
  data/src/main/java/com/hihihihi/data/remote/datasource/QuoteRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/QuoteRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/QuoteRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/repository/QuoteRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/quote/DeleteQuoteUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/quote/UpdateQuoteUseCase.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailTabs.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/EditQuoteDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/QuotesTab.kt
  presentation/src/main/java/com/hihihihi/gureumpage/widgets/heatmap/HistoryHeatMapWidget.kt
Labels: Feature

#147 [Feat] 리마인더 알림 기능 구현
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/hihihihi/gureumpage/GureumApp.kt
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/NotificationModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/DailyReminderWorker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/common/Channels.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/common/GureumMessagingService.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/common/NotificationFactory.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/schema/PushPayload.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/Picker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashScreen.kt
Labels: Feature

#149 [Hotfix] 온보딩 화면 닉네임 저장 로직 수정
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/OnBoardingScreen.kt
Labels: Fix

#148 [Feat] 히트맵 위젯 (4-b) 로직 및 UI 수정
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/widgets/heatmap/DummyData.kt
  presentation/src/main/java/com/hihihihi/gureumpage/widgets/heatmap/HistoryHeatMapWidget.kt
  presentation/src/main/java/com/hihihihi/gureumpage/widgets/heatmap/HistoryHeatMapWorker.kt
Labels: Feature

#151 [Feat] floatingwindow 구현 임시 완료
  data/src/main/java/com/hihihihi/data/local/datasource/TimerLocalDataSource.kt
  data/src/main/java/com/hihihihi/data/local/datasourceimpl/TimerLocalDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/UserBookRemoteDataSourceImpl.kt
  domain/src/main/java/com/hihihihi/domain/model/Timer.kt
  domain/src/main/java/com/hihihihi/domain/repository/FloatingActionRepository.kt
  domain/src/main/java/com/hihihihi/domain/repository/TimerRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/timer/ClearTimerStateUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/timer/GetTimerStateUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/timer/ObserveFloatingActionsUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/timer/ObserveTimerStateUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/timer/RestoreTimerStateUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/timer/SaveTimerStateUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/timer/SendFloatingActionUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/userbook/GetUserBookByIdUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/FloatingTimerService.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/FloatingTimer.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/FloatingTimerService.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/FloatingTouchListener.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerRepository.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerViewModel.kt
  presentation/src/main/res/drawable/ic_cloud_icon_backround.png
Labels: Feature

#153 [Refactor] 위젯 ui 업데이트
  presentation/src/main/java/com/hihihihi/gureumpage/widgets/reading/CurrentReadingBooksWidget.kt
  presentation/src/main/res/xml/current_reading_book_widget_info.xml
  presentation/src/main/res/xml/current_reading_books_widget_info.xml
Labels: Refactoring

#150 [Feat] 앱 알림 구현
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/SummaryModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/NavigationRoute.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/common/GureumMessagingService.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/common/NotificationFactory.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/progress/DailyGoalNotifier.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/progress/Goal80ReminderScheduler.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/progress/Goal80ReminderWorker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/reminder/DailyReminderWorker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/reminder/ReminderScheduler.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/MonthlySummaryWorker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/SummaryProvider.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/SummaryProviderImpl.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/SummaryScheduler.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/WeeklySummaryWorker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/YearlySummaryWorker.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
Labels: Feature

#154 [Refactor] 닉네임 검증 통일, 백버튼 이벤트 및 UI 수정 등
  presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Expansion.kt
  presentation/src/main/java/com/hihihihi/gureumpage/common/utils/NicknameValidator.kt
  presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/common/GureumMessagingService.kt
  presentation/src/main/java/com/hihihihi/gureumpage/notification/common/NotificationFactory.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailTabs.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/SearchBarWithBackground.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/component/NicknameChangeDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/OnBoardingScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/OnBoardingViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/pages/NicknamePage.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/SearchTopAppBar.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/FloatingTimer.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/component/TimerControls.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/component/TimerRing.kt
  presentation/src/main/java/com/hihihihi/gureumpage/widgets/reading/CurrentReadingBookWidget.kt
  presentation/src/main/res/drawable/ic_text_clear_dark.xml
  presentation/src/main/res/drawable/ic_text_clear_light.xml
Labels: Refactoring

#155 [Refactor] 고봉밥 2차 수정사항 리팩토링
  data/src/main/java/com/hihihihi/data/local/datasource/UserPreferencesLocalDataSource.kt
  data/src/main/java/com/hihihihi/data/local/datasourceimpl/UserPreferencesLocalDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasource/DailyReadPageRemoteDataSource.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/DailyReadPageRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/MindmapNodeRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/datasourceimpl/SearchRemoteDataSourceImpl.kt
  data/src/main/java/com/hihihihi/data/remote/service/SearchApiService.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/DailyReadPageRepositoryImpl.kt
  data/src/main/java/com/hihihihi/data/repotisoryimpl/UserPreferencesRepositoryImpl.kt
  domain/src/main/java/com/hihihihi/domain/repository/DailyReadPageRepository.kt
  domain/src/main/java/com/hihihihi/domain/repository/UserPreferencesRepository.kt
  domain/src/main/java/com/hihihihi/domain/usecase/daily/GetDailyReadPagesUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/statistics/GetCategoryStatisticsUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/user/GetLastProviderUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/user/GetMyPageDataUseCase.kt
  domain/src/main/java/com/hihihihi/domain/usecase/user/SetLastProviderUseCase.kt
  functions/delete-user.js
  functions/index.js
  functions/utils/push.js
  functions/utils/triggers.js
  presentation/src/main/java/com/hihihihi/gureumpage/designsystem/theme/GureumColors.kt
  presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailTabs.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/LoginScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/LoginUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/login/components/SocialLoginButton.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/MyPageScreen.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/MyPageUiState.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/MypageViewModel.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/component/MyPageCalendarSection.kt
  presentation/src/main/java/com/hihihihi/gureumpage/ui/mypage/component/MyPageUserProfileCard.kt
  presentation/src/main/java/com/hihihihi/gureumpage/widgets/heatmap/HistoryHeatMapWidget.kt
  presentation/src/main/res/drawable/ic_library_reading.xml
  presentation/src/main/res/drawable/preview_2_a.png
  presentation/src/main/res/drawable/preview_2_b.png
  presentation/src/main/res/drawable/preview_4_b.png
  presentation/src/main/res/drawable/preview_widget_2_b.png
  presentation/src/main/res/values-night/colors.xml
  presentation/src/main/res/values/colors.xml
Labels: Feature, Refactoring
